//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMedicalMVC
{
    using iMedicalMVC.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iMedicalDbContext : DbContext
    {
        public iMedicalDbContext()
            : base("name=iMedicalDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billing_tenure> Billing_tenure { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Contract_Type> Contract_Type { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Employee_Type> Employee_Type { get; set; }
        public virtual DbSet<Job_Type> Job_Type { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Medic_details> Medic_details { get; set; }
        public virtual DbSet<Medical_examination> Medical_examination { get; set; }
        public virtual DbSet<Medical_examination_type> Medical_examination_type { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Payment_Details> Payment_Details { get; set; }
        public virtual DbSet<Prescription> Prescription { get; set; }
        public virtual DbSet<Referral> Referral { get; set; }
        public virtual DbSet<Status_cod> Status_cod { get; set; }
        public virtual DbSet<Tenure_type> Tenure_type { get; set; }
        public virtual DbSet<Title_Type> Title_Type { get; set; }
        public virtual DbSet<Visit> Visit { get; set; }
        public virtual DbSet<Visit_type> Visit_type { get; set; }
    }
}
