//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMedicalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medic_details
    {
        public int Id_Details { get; set; }
        public Nullable<int> ID_Medical_examination { get; set; }
        public string Result_1 { get; set; }
        public string Result_2 { get; set; }
        public string Result_3 { get; set; }
        public string Result_4 { get; set; }
        public string Recommendations { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Medical_examination Medical_examination { get; set; }
    }
}
