//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMedicalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_examination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medical_examination()
        {
            this.Medic_details = new HashSet<Medic_details>();
        }
    
        public int ID_Medical_examination { get; set; }
        public Nullable<int> ID_Patient { get; set; }
        public Nullable<int> ID_medical_examination_type { get; set; }
        public string NumberReferral { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DateEpiration { get; set; }
        public string NumberMedicalExamination { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medic_details> Medic_details { get; set; }
        public virtual Medical_examination_type Medical_examination_type { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
