//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMedicalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Details
    {
        public int ID_Payment_Details { get; set; }
        public Nullable<int> ID_Contract { get; set; }
        public Nullable<int> ID_Billing_tenure { get; set; }
        public System.DateTime Payment_date { get; set; }
        public System.DateTime Payment_due_date { get; set; }
        public int Total { get; set; }
        public string Title { get; set; }
        public string Comments { get; set; }
        public string PaymentDetailsNumber { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
