//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMedicalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public int ID_Referral { get; set; }
        public Nullable<int> ID_Patient { get; set; }
        public Nullable<int> ID_medical_examination_type { get; set; }
        public string Referral_number { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public Nullable<int> ReferralCod { get; set; }
        public string Description { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
