//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMedicalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visit()
        {
            this.Prescription = new HashSet<Prescription>();
        }
    
        public int ID_Visit { get; set; }
        public Nullable<int> ID_Patient { get; set; }
        public Nullable<int> ID_Visit_type { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public Nullable<System.DateTime> Registration_date { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Date_hour_visit_start { get; set; }
        public Nullable<System.DateTime> Data_hour_visit_end { get; set; }
        public Nullable<bool> Status { get; set; }
        public string VisitNumber { get; set; }
        public string Activities_performed { get; set; }
        public string Recomendations { get; set; }
        public string General_information { get; set; }
        public string Dosage_of_medication { get; set; }
        public string Comments2 { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescription { get; set; }
        public virtual Status_cod Status_cod { get; set; }
        public virtual Visit_type Visit_type { get; set; }
    }
}
